version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SIMILARITY_THRESHOLD=0.7
      - MAX_THEMES=100
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=app.db 